FROM ghcr.io/dockhippie/alpine:3.23-amd64@sha256:2e99f2eadcdc47ce11cd6fdef2565a05d261ff1c7bf5f7705f4fdd1df3ab0389

VOLUME ["/var/lib/znc"]
EXPOSE 8080 6667

WORKDIR /var/lib/znc
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/znc && \
  groupadd -g 1000 znc && \
  useradd -u 1000 -d /var/lib/znc -g znc -s /bin/bash -m znc && \
  apk add znc znc-extra && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
