FROM ghcr.io/dockhippie/alpine:3.23-amd64@sha256:2c004c3066c04ee318d4839c43f015e1de28ad370cd4be3cb07bf26a3eccaa6d

VOLUME ["/var/lib/znc"]
EXPOSE 8080 6667

WORKDIR /var/lib/znc
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/znc && \
  groupadd -g 1000 znc && \
  useradd -u 1000 -d /var/lib/znc -g znc -s /bin/bash -m znc && \
  apk add znc znc-extra && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
