FROM ghcr.io/dockhippie/alpine:3.23-arm64@sha256:79f7c1084832a3a66a79b2f8925d3fbdcbc125b01a63c36d8a029868351c2ee8

VOLUME ["/var/lib/znc"]
EXPOSE 8080 6667

WORKDIR /var/lib/znc
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/znc && \
  groupadd -g 1000 znc && \
  useradd -u 1000 -d /var/lib/znc -g znc -s /bin/bash -m znc && \
  apk add znc znc-extra && \
  rm -rf /var/cache/apk/*

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
