FROM ghcr.io/dockhippie/alpine:3.23-arm@sha256:f133eab2c07cb6702b88406dcbc2c2df91504a895e6c6efe0c52d7590b16c274

VOLUME ["/var/lib/znc"]
EXPOSE 8080 6667

WORKDIR /var/lib/znc
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/znc && \
  groupadd -g 1000 znc && \
  useradd -u 1000 -d /var/lib/znc -g znc -s /bin/bash -m znc && \
  apk add znc znc-extra && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
